### ISSUE TITLE
Feat: add 'kusion mod list' to list all available modules in the current workspace.

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#1008]
workspace module example

```yaml
modules:
 opsrule:
    path: "https://ghcr.io/kusionstack/opsrule"
    inspectURL: "https://ghcr.io/kusionstack/opsrule/readme.md"
    version: 0.0.1
    configurations:
        default:
            maxUnavailable: 2
```

The output of this command should be shown in a table which includes fields like name, path, version
