### ISSUE TITLE
Feat: add 'kusion mod inspect' to navigate to the module reference documentation

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#1010]
The destination defaults to the module's URL and can be override by the inspect URL configured in the workspace.yaml

```yaml
modules:
 opsrule:
    path: "https://ghcr.io/kusionstack/opsrule"
    inspectURL: "https://ghcr.io/kusionstack/opsrule/readme.md"
    version: 0.0.1
    configurations:
        default:
            maxUnavailable: 2
```
