### ISSUE TITLE
Feat: update the `runtime` block in workspace

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#1015]
### What would you like to be added?

1. The upgraded workspace is shown as follow:

```yaml
runtimes:
 kubernetes:
    configPath: /etc/kubeconfig.yaml
    context: default
 aws:
    region: us-east-1
    ak: xxxx
    sk: xxxx
```

2. support this runtime field in the module gRPC interface

### Why is this needed?

clarify workspace-scope runtime configurations
