### ISSUE TITLE
Bug: problem of importing resources but cannot get necessary information to use

### ISSUE THREAD

**Issue by hoangndst** [KusionStack/kusion#1272]
### What happened?

For example I have a workspace with a module `mysql` has imported resources like this:
``` yaml
modules:
    mysql:
        path: oci://ghcr.io/viettelcloud/mysql
        version: 0.2.0
        configs:
            default:
                category: basic
                cloud: viettelcloud
                databaseName: quickstart
                importedResources:
                    hashicorp:viettelcloud:viettelcloud_db_instance:test-mysql: test-mysql
```
Then, in stack project, I have `main.k` file like this one to import the existing MySQL instance name test-mysql.
```k
quickstart: ac.AppConfiguration {
    workload: service.Service {
        containers: {
            quickstart: c.Container {
                image: "kusionstack/kusion-quickstart:latest"
                env: {
                    "DB_HOST": "$(KUSION_DB_HOST_QUICKSTART_DEFAULT_QUICKSTART_MYSQL)"
                    "DB_USERNAME": "$(KUSION_DB_USERNAME_QUICKSTART_DEFAULT_QUICKSTART_MYSQL)"
                    "DB_PASSWORD": "$(KUSION_DB_PASSWORD_QUICKSTART_DEFAULT_QUICKSTART_MYSQL)"
                }
            }
        }
    }
    accessories: {
        "network": n.Network {
            ports: [
                n.Port {
                    port: 8080
                }
            ]
        }
        "mysql": mysql.MySQL {
           type: "cloud"
           version: "5.7.30"
           databaseName: "test-mysql"
        }
    }
}
```
With the project above, `kusion` will import the MySQL database instance `test-mysql` to stack. But there is one problem the target of importing the database is to **get the credential information** for the application to connect but after importing the database `test-mysql`, there is **no** necessary credential information.

### What did you expect to happen?

The goal of the import resource feature is to acquire the necessary information for the application's use. There may be alternative methods to store database credentials or similar types of information from other resources.

### How can we reproduce it (as minimally and precisely as possible)?

When creating a shareable resource, it may be necessary to save important information that the application can use in a secret manager.

### Anything else we need to know?

It appears that `kusion generate` does not yet support retrieving secrets from the secret manager.

### Kusion version

<details>

```console
$ kusion version
releaseVersion: 0.12.1+f2ee4522
gitInfo:
    latestTag: v0.12.1
    commit: f2ee4522600ee35227bedcd13a28c9fb1ce6bd9a
    treeState: dirty
buildInfo:
    goVersion: go1.22.3
    GOOS: linux
    GOARCH: amd64
    numCPU: 8
    compiler: gc
    buildTime: "2024-08-16 02:11:56"
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
$ uname -a
Linux buddy 6.8.0-40-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 10:34:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

**Comment by hoangndst** [comment]
cc @liu-hm19 @SparkYuan @ffforest

**Comment by liu-hm19** [comment]
@hoangndst Hi, I've reproduced the problem locally. It seems that Kusion indeed does not import certain sensitive information such as database password when importing some existing cloud resources using `terraform import`. 

I think this should be a feature of the underlying API called by the Terraform provider when importing the resources, more details may find in this [issue](https://github.com/hashicorp/terraform-provider-aws/issues/32159). Therefore, for sensitive information like database passwords that cannot be obtained from the `state` file with `terraform import`, users may need to provide it themselves. 

For example, module generators may create a `random_password` resource to record the password, and for the `mysql` module provided by KusionStack community officially: 

```yaml
# example_workspace.yaml
modules: 
    mysql: 
      path: oci://ghcr.io/kusionstack/mysql
      version: 0.2.0
      configs:
          default: 
            cloud: alicloud
            size: 20
            instanceType: mysql.n2.serverless.1c
            category: serverless_basic
            privateRouting: false
            subnetID: vsw-2ze*******
            databaseName: "wordpress-demo"
            importedResources: 
              "aliyun:alicloud:alicloud_rds_account:wordpress-demo": "rm-2ze*******"
              "aliyun:alicloud:alicloud_db_instance:wordpress-demo": "rm-2ze*******"
              "aliyun:alicloud:alicloud_db_connection:wordpress-demo": "rm-2ze*******"
              "hashicorp:random:random_password:wordpress-demo-mysql": "rds-account-password" # The RDS account password obtained from cloud console or recreated. 
    network:
        path: oci://ghcr.io/kusionstack/network
        version: 0.2.0
        configs:
            default: {}
```

```shell
# Ignore the randomly changed field in random_password to avoid recreate a new one. 
kusion apply --ignore-fields "bcrypt_hash"
```

![image](https://github.com/user-attachments/assets/3bf20121-c68e-4acf-9e1a-1d408e89c407)

And I think it should also be feasible to obtain the credentials through **Secrets Manager**. We can further explore this scenario and provide a demo for other users. cc @ffforest
