### ISSUE TITLE
Unexpected release result when receiving termination signal during `kusion apply` process

### ISSUE THREAD

**Issue by Yangyang96** [KusionStack/kusion#1273]
### What happened?

I had to stop the `kusion apply` process due to an `ImagePullErr` error that appeared during deployment.  When I tried the `kusion apply` command again, it was showing `all resources are reconciled. No diff found.` The `kusion destroy` was also not working in this case with `No managed resources to destroy` indicated. I can no longer manage the resource deployment using `kusion` in this case. The code below is from the release file, and although `spec` is empty, `state` is shown as succeeded.
```yaml
project: quickstart
workspace: dev
revision: 6
stack: default
spec:
    resources: []
    secretStore:
        provider: null
    context: {}
state:
    resources: []
phase: succeeded
```

### What did you expect to happen?

Receiving a termination signal during `kusion apply` should be treated the same as normal apply failure.

### How can we reproduce it (as minimally and precisely as possible)?

1. Use `kusion apply` as usual.
2. Terminate this process halfway.
3. Retry `kusion apply` and `kusion destroy`.

### Kusion version

<details>

```console
$ kusion version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>
