### ISSUE TITLE
Feat: project.yaml is not required

### ISSUE THREAD

**Issue by howieyuen** [KusionStack/kusion#140]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. cd `appops/guestbook-frontend` of konfig, delete `project.yaml`
2. cd `prod` stack, execute `kusion compile`

### 2. What did you expect to see? (Required)

error: project is not provided

### 3. What did you see instead (Required)

nothing printed, compile success

### 4. What is your KusionStack components version? (Required)

```
releaseVersion: v0.6.1
gitInfo:
    latestTag: v0.6.1
    commit: c5eea56957d986ce8914187868dd6901ef0cfd26
    treeState: clean
buildInfo:
    goVersion: go1.17.13
    GOOS: linux
    GOARCH: amd64
    numCPU: 2
    compiler: gc
    buildTime: "2022-09-05 02:45:23"
dependency:
    kclvmgoVersion: v0.4.3-alpha.3
    kclPluginVersion: v0.4.1-alpha2
```
