### ISSUE TITLE
kusion compile -o option produces error

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/kusion#205]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
git clone https://github.com/KusionStack/konfig
cd konfig
kusion compile -w appops/guestbook-frontend/pre -o output.yaml
```

### 2. What did you expect to see? (Required)

compiled result in `output.yaml` file

### 3. What did you see instead (Required)

```
 ❌  KCL Runtime Error[E3M38] : Evaluation failure
      ---> File /Users/amy/work/open/konfig/appops/guestbook-frontend/pre/main.k:5
      5 |appConfiguration: frontend.Server { -> Failure
      attribute 'mainContainer' of Server is required and can't be None or Undefined
```

### 4. What is your KusionStack components version? (Required)

```
kusion version
releaseVersion: v0.7.2
gitInfo:
    latestTag: v0.7.2
    commit: fb996130c1e4a8a30da7c04e672433ea6c870384
    treeState: clean
buildInfo:
    goVersion: go1.17.13
    GOOS: linux
    GOARCH: amd64
    numCPU: 2
    compiler: gc
    buildTime: "2022-12-02 07:00:28"
dependency:
    kclvmgoVersion: v0.4.4-alpha.1
    kclPluginVersion: v0.4.1-alpha2
```
