### ISSUE TITLE
kusion prevew flag `--ignore-fields` support more than map[string]interface{} type

### ISSUE THREAD

**Issue by howieyuen** [KusionStack/kusion#241]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I wanna to ignore k8s Service of `spec.ports[*].targetPort`, but ports is a slice type, now kusion references `pkg/apis/meta/v1/unstructured`, its supports `map[string]interface{}` only.

```yaml
# ignore spec.ports.targetPort
apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: bar
spec:
  clusterIP: 172.16.128.40
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP
```

**Describe the feature you'd like:**

Support more then map type

**Describe alternatives you've considered:**

Extends unstructured pkg

**Teachability, Documentation, Adoption, Migration Strategy:**

Do research on how json path work
