### ISSUE TITLE
pkg/util/gitutil use `git` command may cause not found error

### ISSUE THREAD

**Issue by howieyuen** [KusionStack/kusion#247]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`kusion version`

### 2. What did you expect to see? (Required)
```yaml
releaseVersion: v0.7.2+0a095c4d
gitInfo:
    latestTag: v0.7.2
    commit: 0a095c4d21ec6cf5f63d83341bdd80d15c6df59a
    treeState: clean
buildInfo:
    goVersion: go1.19.5
    GOOS: darwin
    GOARCH: amd64
    numCPU: 12
    compiler: gc
    buildTime: "2023-02-15 16:28:24"
dependency:
    kclvmgoVersion: v0.4.3
    kclPluginVersion: v0.2.20

```

### 3. What did you see instead (Required)

```bash
Username for 'https://code.alipay.com':
```
