### ISSUE TITLE
kusion watch cannot see pod details

### ISSUE THREAD

**Issue by howieyuen** [KusionStack/kusion#253]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`kusion apply --yes --watch`

### 2. What did you expect to see? (Required)

kusion print Deplotment, ReplicaSet and Pod details

### 3. What did you see instead (Required)

1. No Pod details
2. Clean all screen buffer 

### 4. What is your KusionStack components version? (Required)

```yaml
releaseVersion: v0.7.3
gitInfo:
    latestTag: v0.7.3
    commit: ff024296f4961d00083df14c89ce1dd80030cff5
    treeState: dirty
buildInfo:
    goVersion: go1.18.9
    GOOS: linux
    GOARCH: amd64
    numCPU: 2
    compiler: gc
    buildTime: "2023-01-09 04:04:26"
dependency:
    kclvmgoVersion: v0.4.4-beta.2
    kclPluginVersion: v0.4.1-alpha2
```
