### ISSUE TITLE
Documentation: Update the example about integrating kusion with ArgoCD

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#404]
### What would you like to be added?

Update the example about integrating kusion with ArgoCD

### Why is this needed?

The [ArgoCD example](https://kusionstack.io/docs/user_docs/guides/argocd/drift-detection-by-argocd) on the website has become outdated and requires updating.

**Comment by howieyuen** [comment]
There are 3 questions are worth thinking
1. kusion `compile` cannot generate raw k8s yaml by "stdout", a hint message print first, "Generating Spec in the Stack dev..."
2. Examples project from konfig are default with "Spec" output. Take "nginx-example" to say, set `__konfig_output_format__` to `raw`, the compiled result as below is unexpected:
```yaml
- id: ""
  type: ""
  attributes: {}
- id: ""
  type: ""
  attributes: {}
- id: ""
  type: ""
  attributes: {}
```
3. kusion and argocd are both working on "CD", seek a better integration is more valuable.
