### ISSUE TITLE
Bugfix: Apply failed when k8s resource namespace is not explicitly specified

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#411]
### What happened?

According to the k8s convention, the resource namespace is regarded as `default` when it is not explicitly specified. Kusion will throw an error in this scenario.

<img width="835" alt="image" src="https://github.com/KusionStack/kusion/assets/4793557/d6021fc9-1877-4f78-952f-cff7f0278a18">

### What did you expect to happen?

Apply success

### How can we reproduce it (as minimally and precisely as possible)?

apply a resource directly from a spec.yaml and this resource namespace is not set

```yaml
- id: apps/v1:Deployment:default:nginx-deployment
  type: Kubernetes
  attributes:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - image: nginx:1.14.2
            name: nginx
            ports:
            - containerPort: 80
```

### Kusion version

<details>

```console
$ kusion version
# paste output here
```
v0.8.2

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64
</details>

### Install tools

<details>

</details>
