### ISSUE TITLE
Concurrent execute `kusion compile` error

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/kusion#75]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

After concurrent execute `kusion compile` for a period of time.

### 2. What did you expect to see? (Required)

Normal compilation without error

### 3. What did you see instead (Required)

![image](https://user-images.githubusercontent.com/9360247/174216181-96ac5a33-928a-4ec3-b85d-e9d809909339.png)

### 4. What is your KusionStack components version? (Required)

```
releaseVersion: v0.4.2-alpha.1
gitInfo:
    latestTag: v0.4.2-alpha.1
    commit: 28b4f935cdd2813f5e7c09de855f6e584ed4af3c
    treeState: clean
buildInfo:
    goVersion: go1.17.10
    GOOS: linux
    GOARCH: amd64
    numCPU: 2
    compiler: gc
    buildTime: "2022-05-26 08:37:19"
dependency:
    kclvmgoVersion: v0.4.2-alpha4
    kclPluginVersion: v0.4.1-alpha2
```
